### ISSUE TITLE
fix(scheduled auction displayed twice)

### ISSUE THREAD

**Issue by clesaege** [kleros/dutchx#2]
![missaligned](https://user-images.githubusercontent.com/8873352/69075330-188c3480-0a29-11ea-8f18-f07973fbbf01.png)

**Comment by clesaege** [comment]
![missaligned](https://user-images.githubusercontent.com/8873352/69075955-5b024100-0a2a-11ea-9858-929d6b9d5b6e.png)
Also the case for running options.

**Comment by eccentricexit** [comment]
This is no longer reproducible and seems to have been fixed in a previous commit. Please reopen if it happens again.
