### ISSUE TITLE
fix(bids are unclaimable)

### ISSUE THREAD

**Issue by clesaege** [kleros/dutchx#7]
Impossible to withdraw in slow.trade
![missaligned](https://user-images.githubusercontent.com/8873352/69101918-d549ba00-0a58-11ea-84a7-b49ddc956404.png)
nor in fairdex
![toclaim](https://user-images.githubusercontent.com/8873352/69102436-5c4b6200-0a5a-11ea-81a1-da112f164b0e.png)

**Comment by eccentricexit** [comment]
Fixed on commit [36ff09](https://github.com/kleros/fairdex/commit/36ff091b3c2f819464e992defd963aed619e99cd)
